version: '3.2'
services:
  info:
    container_name: sonm-ico-info
    build: info
    ports:
      - "1234:8000"
    env_file:
      - ./pg.env
  invoice:
    container_name: sonm-ico-invoice
    build: invoice
    ports:
      - "1234:8001"
    env_file:
      - ./pg.env
  tx-monitor:
    container_name: sonm-ico-tx-monitor
    build: tx-monitor
    env_file:
      - ./pg.env
