name:        api
version:     "0.0"
synopsis:    ICO multi currency payments
license:     MIT
author:      Max Taldykin
maintainer:  <max@formalmethods.ru>
category:    Development

dependencies:
  - base
  - aeson
  - containers
  - http-types
  - postgresql-simple
  - resource-pool
  - scotty
  - text
  - vector
  - wai-cors

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards

ghc-options:
  - -Wall
  - -threaded
  - -O2
  - -funbox-strict-fields

executables:
  api:
    source-dirs: src
    main: Main.hs
