name:        monitor
version:     "0.0"
synopsis:    Monitors addresses and transactions
license:     MIT
author:      Max Taldykin
maintainer:  <max@formalmethods.ru>
category:    Development

dependencies:
  - base
  - aeson
  - bytestring
  - configurator
  - containers
  - lens
  - lens-aeson
  - postgresql-simple
  - resource-pool
  - text
  - websockets
  - wuss
  - unix

default-extensions:
  - LambdaCase
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - OverloadedStrings
  - RecordWildCards

ghc-options:
  - -Wall
  - -threaded
  - -O2
  - -funbox-strict-fields

executables:
  monitor:
    source-dirs: src
    main: Main.hs
